// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaKJtV-zyKyDQr8coSlFprp-JXAJFNfWc',
    appId: '1:363541675424:web:551216721ca8421931b8c5',
    messagingSenderId: '363541675424',
    projectId: 'spotifyclone-b44b8',
    authDomain: 'spotifyclone-b44b8.firebaseapp.com',
    storageBucket: 'spotifyclone-b44b8.appspot.com',
    measurementId: 'G-HJWYZ7RE4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj54Bh3MYYb86XU8MRfzBP6h2f8bt0tks',
    appId: '1:363541675424:android:6256720b9a754f9b31b8c5',
    messagingSenderId: '363541675424',
    projectId: 'spotifyclone-b44b8',
    storageBucket: 'spotifyclone-b44b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCU7dIVatayTDyDqhG1e6mAu8rKPOfjDoM',
    appId: '1:363541675424:ios:72d7db2fab87f15031b8c5',
    messagingSenderId: '363541675424',
    projectId: 'spotifyclone-b44b8',
    storageBucket: 'spotifyclone-b44b8.appspot.com',
    iosBundleId: 'com.example.spotify',
  );
}
